#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"
solana-test-validator --ticks-per-slot 10 -r \
	--bpf-program srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX ./programsAndAccounts/openbook_dex.so \
	--bpf-program 675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8 ./programsAndAccounts/raydium_amm_program.so \
	--account 9DCxsMizn3H1hprZ7xWe6LDzeUeZBksYFpBWBtSf1PQX ./programsAndAccounts/raydium_config_data.json \
	--account 7YttLkHDoNj9wyDur5pM1ejNaAvT9X4eqaYcHQqtj2G5 ./programsAndAccounts/raydium_fee_receiver_ata.json \
	--account 9wH1zyNmmTTPsfc6RoHMw3R6REritb6TysoxtVLgE7xY ./programsAndAccounts/mint01.json \
	--account BFosTuBNFqHLN2dsxT4kbFEzZZ4SGLrdxVkNvZAPr96Q ./programsAndAccounts/mint01Ata.json \
	--account 3BY6DvyFPU8EpoGjgu3zWR2vuYEuKePCWTo4m7yAZKua ./programsAndAccounts/market01.json \
	--bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ./programsAndAccounts/mpl_token_metadata.so
